name: manish_flutter_portfolio
description: "Manish Kumar Agrahari - Flutter Developer Portfolio"
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.3.1
  google_fonts: ^8.0.2
  riverpod_annotation: ^4.0.2
  go_router: ^17.2.1
  flutter_animate: ^4.5.2
  visibility_detector: ^0.4.0+2
  url_launcher: ^6.3.2
  http: ^1.6.0
  flutter_markdown: ^0.7.7+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  riverpod_generator: ^4.0.3
  build_runner: ^2.13.1
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: false
  web:
    generate: true
    image_path: "assets/icons/app_icon.png"
    background_color: "#080C14"
    theme_color: "#00D4FF"
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

